
name: MySlimefunAddon
author: dragondirt
description: Add random Slimefun mob drops
main: me.CHANGEME.myslimefunaddon.MySlimefunAddon
website: https://github.com/DragonTSO/SlimefunpluginsTutorial

version: ${project.version}
api-version: 1.14

depend:
- Slimefun
